dist: xenial
language: node_js
node_js:
  - lts/*
cache: npm
before_install:
  - sudo apt update
  - sudo apt install -y chromium-browser
install:
  - npm install
script:
  - npm run test-headless
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  verbose: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist/Pinterest
  on:
    branch: master
